dist: bionic
language: go
services:
  - docker
jobs:
  include:
    - stage: lint & unit tests
      script: echo 'test lint & unit ok'
    - stage: e2e tests
      script:
        - make image-build
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mkdir -p /usr/local/bin/ && sudo install minikube /usr/local/bin/
        - sudo snap install kubectl --classic
        - make test-cluster-up && kubectl get pods -A
        - make yaml-deploy
        - kubectl wait --for=condition=Ready pod dropbox-pod --timeout=300s
        - sleep 10
        - kubectl exec -it dropbox-pod -- ls /var/www/html | grep e2e_test_file > /dev/null
      after_script:
        - make yaml-clean
        - make test-cluster-clean
